# -*- coding: utf-8 -*-
"""ww-question1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X_BAGdfPYmOL1oJuqMwMWNstU-U7ZccM

Question 1:
----------

There is a file containing a word and its possible meanings (like a Dictionary). The contents of the file look like this:

Apple – a fruit, a tech firm
Table – an object, contains rows and columns when used in context of computers
Orange – a fruit

Given a path to the file, do the following:

a)    Create a method called doesFileExist(String path) which takes the path of the file and tells the user if the file exists at that path or not. Assume all paths are relative to your project structure. If the file does not exist, catch the requisite exception.
b)    Read each word and its possible meanings and print them out. Your output should look like this:

Word1
Meaning 1
Meaning 2
Word2
Meaning1
Meaning2

Use appropriate data structures wherever necessary.
"""

import os

### The exercise was developed in Google Colab. 
### To import a file from Google Drive the following steps were followed

# from google.colab import drive
# drive.mount('/content/gdrive')

### The location of the project in Google Drive
# os.chdir('/content/gdrive/My Drive/Colab Notebooks')

# Part a: Checks if the file exists. Takes as input a file path
def doesFileExist(path):
  exists = os.path.exists(path)
  if exists:
    print('File exists')
  else:
    print('File does not exist')
    
  return exists

# Part b: Prints word and its meanings from an input file path
def printDictionary(filepath):
  
  with open(filepath, 'r') as file:
    # Read contents from the file
    content=file.readlines()
    for line in content:
      # Split word and its meanings from the line
      part = line.split(' - ')
      word = part[0]
      print (word)
      # Split string of meanings into multiple separate meanings
      meanings = part[1].split(', ')
      for meaning in meanings:
        print (meaning.rstrip())

if __name__ == '__main__':
  # User-defined dictionary file
  user_path = input()
  exists = doesFileExist(user_path)
  if exists:
    printDictionary(user_path)

