# -*- coding: utf-8 -*-
"""ww-question3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQY2YFE-hh3J0ZexOAt557NeBeLVc7lW

Question 3:
----------

Generate 500 random numbers and create a method to print the nth smallest number in a programming language of your choice. 8
"""

import random

# Generate 500 random numbers 
def random_number():

  # create empty list
  unsorted_numbers = []
  
  # populate unsorted_numbers
  for i in range (500):
    num = random.randint(1, 10000)
    unsorted_numbers.append(num)
    
  return unsorted_numbers  

# Find the smallest number
def smallest(numbers, nth_value):
  
  # raise exception if the nth smallest number is less than 0 or greater than 500  
  if nth_value <= 0 or nth_value > len(numbers):
    raise ValueError("Invalid Number. Enter number between 1 and 500")
    
  else:
    print("Generating the smallest {}-th value".format(nth_value))
    # sort the numbers generated
    numbers.sort()
    print('Sorted numbers: {}'.format(numbers))
    # get the samllest nth number
    smallest_number = numbers[nth_value-1]
    return smallest_number

# Test Cases  
numbers = random_number()
print('Generated numbers: {}'.format(numbers))
try:
  s = smallest(numbers,0)
  print(s)
except ValueError as e:
  print(e)
  
try:
  s = smallest(numbers,5)
  print(s)
except ValueError as e:
  print(e)

